export const wallConfig = {
  capacity: 200,
  firstShortCode: 101,
  persistenceFile: 'data/wall-entries.json',
  localFallbackKey: 'bosch_collective_wall_v2',
  reservationFallbackKey: 'bosch_collective_wall_codes_v2',
  websocketPath: '/api/wall/ws',
  layout: {
    referenceWidthPx: 1920,
    referenceHeightPx: 1080,
    columns: 20,
    rows: 10,
    cellWidthPx: 106,
    cellHeightPx: 83,
    cellGapPx: 5,
    placeholderOpacity: 0.04,
    standbyGlowOpacity: 0.07,
    standbyGlowPeriodMs: 2000,
    standbyGlowMinSlots: 3,
    standbyGlowMaxSlots: 5,
  },
  breathing: {
    amplitudePx: 3,
    periodMsMin: 4000,
    periodMsMax: 6500,
    scaleAmplitude: 0.015,
  },
  joinAnimation: {
    recedeMs: 600,
    enterMs: 1200,
    perceptionMs: 1500,
    labelMs: 1500,
    holdMs: 2000,
    settleMs: 1500,
    rippleMs: 1000,
    multiPersonStaggerMs: 150,
    queueBusyThreshold: 3,
    queueRushThreshold: 6,
  },
  lookup: {
    holdMs: 8000,
    notFoundMs: 2000,
  },
  reconnect: {
    initialDelayMs: 750,
    maxDelayMs: 8000,
  },
} as const;
